name: Build AX6S via ImageBuilder

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install ImageBuilder Dependencies
      run: |
        sudo apt-get -qq update
        # 额外补充 zstd 构建和解压依赖，完美适配官方新老格式
        sudo apt-get -qq install -y build-essential libncurses-dev zlib1g-dev gawk git gettext libssl-dev xsltproc rsync wget unzip qemu-utils zstd

    - name: Download and Extract ImageBuilder
      run: |
        # 智能化双模判定：兼容官方将快照版打包格式从 .tar.xz 切换为 .tar.zst 的底层变更
        cd $GITHUB_WORKSPACE
        if wget --spider https://downloads.immortalwrt.org/snapshots/targets/mediatek/mt7622/immortalwrt-imagebuilder-mediatek-mt7622.Linux-x86_64.tar.zst; then
          echo "检测到官方最新的 ZST 高速压缩格式，启动下载..."
          wget https://downloads.immortalwrt.org/snapshots/targets/mediatek/mt7622/immortalwrt-imagebuilder-mediatek-mt7622.Linux-x86_64.tar.zst
          tar -xf immortalwrt-imagebuilder-mediatek-mt7622.Linux-x86_64.tar.zst
        else
          echo "未检测到 ZST 格式，自动降级拉取传统 XZ 格式..."
          wget https://downloads.immortalwrt.org/snapshots/targets/mediatek/mt7622/immortalwrt-imagebuilder-mediatek-mt7622.Linux-x86_64.tar.xz
          tar -Jxf immortalwrt-imagebuilder-mediatek-mt7622.Linux-x86_64.tar.xz
        fi

    - name: Build Firmware with Daed and LuCI
      run: |
        cd immortalwrt-imagebuilder-mediatek-mt7622.Linux-x86_64
        
        # 强制注入网页服务、全套中文包、Daed核心及关键网络驱动
        PACKAGES="luci luci-i18n-base-zh-cn luci-app-daed luci-i18n-daed-zh-cn kmod-veth kmod-xdp-sockets-diag"
        
        # 极速打包红米 AX6S
        make image PROFILE=xiaomi_redmi-router-ax6s PACKAGES="$PACKAGES"

    - name: Upload Firmware to Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ImmortalWrt_AX6S_Daed_ImageBuilder
        path: immortalwrt-imagebuilder-mediatek-mt7622.Linux-x86_64/bin/targets/mediatek/mt7622/*-sysupgrade.itb
